# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/melisha/code/cppTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/melisha/code/cppTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/melisha/code/cppTest/CMakeFiles /home/melisha/code/cppTest//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/melisha/code/cppTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

client/Client.o: client/Client.cpp.o
.PHONY : client/Client.o

# target to build an object file
client/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/Client.cpp.o
.PHONY : client/Client.cpp.o

client/Client.i: client/Client.cpp.i
.PHONY : client/Client.i

# target to preprocess a source file
client/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/Client.cpp.i
.PHONY : client/Client.cpp.i

client/Client.s: client/Client.cpp.s
.PHONY : client/Client.s

# target to generate assembly for a file
client/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/Client.cpp.s
.PHONY : client/Client.cpp.s

client/main.o: client/main.cpp.o
.PHONY : client/main.o

# target to build an object file
client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.o
.PHONY : client/main.cpp.o

client/main.i: client/main.cpp.i
.PHONY : client/main.i

# target to preprocess a source file
client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.i
.PHONY : client/main.cpp.i

client/main.s: client/main.cpp.s
.PHONY : client/main.s

# target to generate assembly for a file
client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/client/main.cpp.s
.PHONY : client/main.cpp.s

pkg/logger/Logger.o: pkg/logger/Logger.cpp.o
.PHONY : pkg/logger/Logger.o

# target to build an object file
pkg/logger/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/pkg/logger/Logger.cpp.o
.PHONY : pkg/logger/Logger.cpp.o

pkg/logger/Logger.i: pkg/logger/Logger.cpp.i
.PHONY : pkg/logger/Logger.i

# target to preprocess a source file
pkg/logger/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/pkg/logger/Logger.cpp.i
.PHONY : pkg/logger/Logger.cpp.i

pkg/logger/Logger.s: pkg/logger/Logger.cpp.s
.PHONY : pkg/logger/Logger.s

# target to generate assembly for a file
pkg/logger/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logger.dir/build.make CMakeFiles/logger.dir/pkg/logger/Logger.cpp.s
.PHONY : pkg/logger/Logger.cpp.s

pkg/parser/parser.o: pkg/parser/parser.cpp.o
.PHONY : pkg/parser/parser.o

# target to build an object file
pkg/parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/pkg/parser/parser.cpp.o
.PHONY : pkg/parser/parser.cpp.o

pkg/parser/parser.i: pkg/parser/parser.cpp.i
.PHONY : pkg/parser/parser.i

# target to preprocess a source file
pkg/parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/pkg/parser/parser.cpp.i
.PHONY : pkg/parser/parser.cpp.i

pkg/parser/parser.s: pkg/parser/parser.cpp.s
.PHONY : pkg/parser/parser.s

# target to generate assembly for a file
pkg/parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/pkg/parser/parser.cpp.s
.PHONY : pkg/parser/parser.cpp.s

server/Server.o: server/Server.cpp.o
.PHONY : server/Server.o

# target to build an object file
server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Server.cpp.o
.PHONY : server/Server.cpp.o

server/Server.i: server/Server.cpp.i
.PHONY : server/Server.i

# target to preprocess a source file
server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Server.cpp.i
.PHONY : server/Server.cpp.i

server/Server.s: server/Server.cpp.s
.PHONY : server/Server.s

# target to generate assembly for a file
server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/Server.cpp.s
.PHONY : server/Server.cpp.s

server/main.o: server/main.cpp.o
.PHONY : server/main.o

# target to build an object file
server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.o
.PHONY : server/main.cpp.o

server/main.i: server/main.cpp.i
.PHONY : server/main.i

# target to preprocess a source file
server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.i
.PHONY : server/main.cpp.i

server/main.s: server/main.cpp.s
.PHONY : server/main.s

# target to generate assembly for a file
server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/server/main.cpp.s
.PHONY : server/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Client"
	@echo "... Server"
	@echo "... logger"
	@echo "... parser"
	@echo "... client/Client.o"
	@echo "... client/Client.i"
	@echo "... client/Client.s"
	@echo "... client/main.o"
	@echo "... client/main.i"
	@echo "... client/main.s"
	@echo "... pkg/logger/Logger.o"
	@echo "... pkg/logger/Logger.i"
	@echo "... pkg/logger/Logger.s"
	@echo "... pkg/parser/parser.o"
	@echo "... pkg/parser/parser.i"
	@echo "... pkg/parser/parser.s"
	@echo "... server/Server.o"
	@echo "... server/Server.i"
	@echo "... server/Server.s"
	@echo "... server/main.o"
	@echo "... server/main.i"
	@echo "... server/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

